name: Commit
on:
  push:
    branches-ignore: []
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm run build:doc
      - name: Update README
        uses: ChocolateLoverRaj/npm-version/commit@next
        with:
          files: 'README.md'
          message: 'Generate README.md'
          token: ${{ secrets.GITHUB_TOKEN }}
